"""Legal OSINT network for the Earth zone. Inventory, not a crawl.

Every public / keyed / owned source we intend lives here so the globe
cannot grow a silent adapter. Shipped rows fetch. Keyed rows wait on a
paste. Later rows are next. Out rows are refused — no host in source.

The observer sees what is broadcasting or published. Individual cars,
silent airframes, unpublished cameras, and mid-ocean ships (VHF dies
offshore; we do not buy satellite AIS) are holes, not scrape targets.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

FeedStatus = Literal["shipped", "keyed", "later", "out"]


@dataclass(frozen=True)
class FeedSpec:
    id: str
    layer: str
    status: FeedStatus
    what: str
    hole: str
    host: str = ""
    key: str = ""


FEEDS: tuple[FeedSpec, ...] = (
    FeedSpec(
        "usgs",
        "quakes",
        "shipped",
        "USGS all_day GeoJSON",
        "Below network detection. Delayed.",
        host="earthquake.usgs.gov",
    ),
    FeedSpec(
        "opensky",
        "flights",
        "shipped",
        "OpenSky /api/states/all (every squawk, UAV split; OAuth2 client)",
        "Oceans and remote FIR. Silent airframes stay absent. Not every car. "
        "Standard 4,000 credits/day.",
        host="opensky-network.org",
    ),
    FeedSpec(
        "adsb-mil",
        "military",
        "shipped",
        "adsb.lol /v2/mil public military ADS-B",
        "Silent airframes are a deaf zone.",
        host="adsb.lol",
    ),
    FeedSpec(
        "aisstream",
        "vessels",
        "keyed",
        "AISStream AIS (free key). Paint packets the feed sent, including mid-ocean if mixed.",
        "Worldwide coastal sample. Mid-ocean VHF is deaf. We do not buy a sat-AIS product.",
        host="stream.aisstream.io",
        key="earth.aisstream_key",
    ),
    FeedSpec(
        "celestrak",
        "satellites",
        "shipped",
        "CelesTrak GP TLE + SGP4 (GNSS / weather / visual / science + samples)",
        "Classified objects absent. Starlink / OneWeb / Planet are samples, not painted shells.",
        host="celestrak.org",
    ),
    FeedSpec(
        "radio-browser",
        "radio",
        "shipped",
        "Radio Browser directory geo pins",
        "No audio. Not a transmitter viewshed.",
        host="radio-browser.info",
    ),
    FeedSpec(
        "tfl-jamcam",
        "cameras",
        "shipped",
        "TfL JamCam published positions",
        "Pose unknown unless a prior exists. No stills, no video. Rural is blind.",
        host="api.tfl.gov.uk",
    ),
    FeedSpec(
        "caltrans-cctv",
        "cameras",
        "shipped",
        "Caltrans D1-D12 published CCTV positions + look direction",
        "Rural CA and other states are holes. No still ingest.",
        host="cwwp2.dot.ca.gov",
    ),
    FeedSpec(
        "open-meteo",
        "weather",
        "shipped",
        "Open-Meteo current at city pins",
        "Model grid, not a station mesh.",
        host="api.open-meteo.com",
    ),
    FeedSpec(
        "launches",
        "sites",
        "shipped",
        "Launch Library 2 upcoming pads",
        "Pads without geo are a hole. Not a T-0 clock.",
        host="ll.thespacedevs.com",
    ),
    FeedSpec(
        "firms",
        "fires",
        "keyed",
        "NASA FIRMS hotspots (free MAP_KEY)",
        "Cloud and revisit. Needs a free MAP_KEY. We do not buy a higher tier.",
        host="firms.modaps.eosdis.nasa.gov",
        key="earth.firms_key",
    ),
    FeedSpec(
        "digitraffic",
        "vessels",
        "shipped",
        "Fintraffic Digitraffic AIS (Finnish coast / Baltic, no key)",
        "Not global. Mid-ocean VHF is deaf. We do not buy satellite AIS.",
        host="meri.digitraffic.fi",
    ),
    FeedSpec(
        "eonet",
        "sites",
        "shipped",
        "NASA EONET open natural events (named storms, fires, volcanoes)",
        "Not every incident. Not a face index.",
        host="eonet.gsfc.nasa.gov",
    ),
    FeedSpec(
        "tfl-road",
        "traffic",
        "shipped",
        "TfL Road Disruption (not VINs)",
        "London roads. Individual cars are not a public feed.",
        host="api.tfl.gov.uk",
    ),
    FeedSpec(
        "osm-webcams",
        "cameras",
        "shipped",
        "OSM camera:type=webcam pins worldwide (ODbL, positions only)",
        "Mapper catalog, not a crawl. No stills. Overpass sample boxes on inhabited continents.",
        host="overpass-api.de",
    ),
    FeedSpec(
        "sentinel1-asf",
        "radar",
        "shipped",
        "NASA ASF Sentinel-1 IW GRD catalog, mid-ocean sample (pass footprints)",
        "A frame is not a hull. Sample of recent scenes, not every pass.",
        host="api.daac.asf.alaska.edu",
    ),
    FeedSpec(
        "viirs-boats",
        "radar",
        "later",
        "EOG VIIRS night-light boat detections (CC BY 4.0 when the file is open)",
        "Mines wants a login; NRT is paid. We do not buy EOG NRT. Not a name tag.",
    ),
    FeedSpec(
        "sat-ais",
        "vessels",
        "out",
        "Commercial satellite AIS (Spire, exactEarth, paid MarineTraffic)",
        "Not illegal. We will not pay. Mid-ocean stays empty.",
    ),
    FeedSpec(
        "barentswatch",
        "vessels",
        "keyed",
        "Kystverket / BarentsWatch AIS (free AIS client, Norwegian EEZ + their sats)",
        "Not a global paid sat-AIS product. Fishing <15 m and leisure/sail <45 m withheld.",
        host="live.ais.barentswatch.no",
        key="earth.barentswatch_client_id",
    ),
    FeedSpec(
        "gfw-sar",
        "radar",
        "keyed",
        "Global Fishing Watch unmatched SAR detections (CC BY-NC, local observer)",
        "Industrial-scale metal, ~5 day lag. Not a hull name. Not a resale. "
        "We stop calling GFW near their published rate cap.",
        host="gateway.api.globalfishingwatch.org",
        key="earth.gfw_token",
    ),
    FeedSpec(
        "nyc-dot",
        "cameras",
        "shipped",
        "NYC DOT public map camera positions (one city catalog)",
        "Position only. No stills. Not the globe.",
        host="webcams.nyctmc.org",
    ),
    FeedSpec(
        "sg-lta",
        "cameras",
        "shipped",
        "Singapore LTA traffic-camera positions (data.gov.sg)",
        "Position only. No stills.",
        host="api.data.gov.sg",
    ),
    FeedSpec(
        "fi-weathercam",
        "cameras",
        "shipped",
        "Fintraffic road weather cameras (CC BY 4.0)",
        "Finland roads. Position only. No stills.",
        host="tie.digitraffic.fi",
    ),
    FeedSpec(
        "hk-td",
        "cameras",
        "shipped",
        "Hong Kong Transport Department camera locations",
        "Position only. No stills.",
        host="static.data.gov.hk",
    ),
    FeedSpec(
        "osm-tiles",
        "sites",
        "shipped",
        "OpenStreetMap raster tiles on the disc when Tiles is on (ODbL)",
        "Optional. Never required to see holes. Cache + 2 connections.",
        host="tile.openstreetmap.org",
    ),
    FeedSpec(
        "fi-traffic",
        "traffic",
        "shipped",
        "Fintraffic traffic messages (not VINs)",
        "Finnish roads. Individual cars are not a public feed.",
        host="tie.digitraffic.fi",
    ),
    FeedSpec(
        "aprs",
        "radio",
        "keyed",
        "aprs.fi loc for named stations (https://aprs.fi)",
        "Only callsigns you name (default W1AW). No wildcard, no map scrape.",
        host="api.aprs.fi",
        key="earth.aprs_key",
    ),
    FeedSpec(
        "caltrans-lcs",
        "traffic",
        "shipped",
        "Caltrans lane-closure / work-zone catalog (not VINs)",
        "Individual cars are not a public feed. Other states later.",
        host="cwwp2.dot.ca.gov",
    ),
    FeedSpec(
        "drivebc",
        "traffic",
        "shipped",
        "DriveBC Open511 provincial highway events (OGL-BC)",
        "BC highways. Individual cars are not a public feed.",
        host="api.open511.gov.bc.ca",
    ),
    FeedSpec(
        "nsw-live",
        "traffic",
        "shipped",
        "NSW Live Traffic incident and roadwork GeoJSON",
        "New South Wales roads. Individual cars are not a public feed.",
        host="api.transport.nsw.gov.au",
    ),
    FeedSpec(
        "qld-traffic",
        "traffic",
        "shipped",
        "QLDTraffic events GeoJSON (no key in the public spec)",
        "Queensland roads. Individual cars are not a public feed.",
        host="api.qldtraffic.qld.gov.au",
    ),
    FeedSpec(
        "nzta",
        "traffic",
        "shipped",
        "Waka Kotahi / NZTA traffic events",
        "New Zealand state highways. Individual cars are not a public feed.",
        host="trafficnz.info",
    ),
    FeedSpec(
        "on-511",
        "traffic",
        "shipped",
        "Ontario 511 CARS events",
        "Ontario roads. Individual cars are not a public feed.",
        host="511on.ca",
    ),
    FeedSpec(
        "mb-511",
        "traffic",
        "shipped",
        "Manitoba 511 CARS events",
        "Manitoba roads. Individual cars are not a public feed.",
        host="511.gov.mb.ca",
    ),
    FeedSpec(
        "ns-511",
        "traffic",
        "shipped",
        "Nova Scotia 511 CARS events",
        "Nova Scotia roads. Individual cars are not a public feed.",
        host="511.novascotia.ca",
    ),
    FeedSpec(
        "ab-511",
        "traffic",
        "shipped",
        "Alberta 511 events (public GET; a free developer key is optional)",
        "Alberta roads. Individual cars are not a public feed.",
        host="511.alberta.ca",
    ),
    FeedSpec(
        "sk-511",
        "traffic",
        "shipped",
        "Saskatchewan 511 CARS events",
        "Saskatchewan roads. Individual cars are not a public feed.",
        host="hotline.gov.sk.ca",
    ),
    FeedSpec(
        "fl-511",
        "traffic",
        "shipped",
        "Florida 511 CARS events",
        "Florida roads. Individual cars are not a public feed.",
        host="fl511.com",
    ),
    FeedSpec(
        "ny-511",
        "traffic",
        "shipped",
        "New York 511 CARS events",
        "New York roads. Individual cars are not a public feed.",
        host="511ny.org",
    ),
    FeedSpec(
        "cotrip",
        "traffic",
        "shipped",
        "Colorado COtrip 511 events",
        "Colorado roads. Individual cars are not a public feed.",
        host="www.cotrip.org",
    ),
    FeedSpec(
        "ia-511",
        "traffic",
        "shipped",
        "Iowa 511 CARS events",
        "Iowa roads. Individual cars are not a public feed.",
        host="511ia.org",
    ),
    FeedSpec(
        "mn-511",
        "traffic",
        "shipped",
        "Minnesota 511 CARS events",
        "Minnesota roads. Individual cars are not a public feed.",
        host="511mn.org",
    ),
    FeedSpec(
        "ga-511",
        "traffic",
        "shipped",
        "Georgia 511 CARS events",
        "Georgia roads. Individual cars are not a public feed.",
        host="511ga.org",
    ),
    FeedSpec(
        "nws",
        "weather",
        "shipped",
        "NWS active alerts GeoJSON (User-Agent required, no key)",
        "US / territories. Not a station mesh. Not every warning on Earth.",
        host="api.weather.gov",
    ),
    FeedSpec(
        "ourairports",
        "sites",
        "shipped",
        "OurAirports daily dump — large/medium fields with scheduled service",
        "Not a live radar. Closed and private strips stay off.",
        host="raw.githubusercontent.com",
    ),
    FeedSpec(
        "spacetrack",
        "satellites",
        "keyed",
        "Space-Track GP TLE sample + ISS (free account, official SSA)",
        "Payload sample, not the painted catalog. Classified objects absent.",
        host="www.space-track.org",
        key="earth.spacetrack_user",
    ),
    FeedSpec(
        "swpc-ovation",
        "weather",
        "shipped",
        "NOAA SWPC Ovation aurora forecast cells",
        "Model cells, not a photograph. Polar night still needed.",
        host="services.swpc.noaa.gov",
    ),
    FeedSpec(
        "emsc",
        "quakes",
        "shipped",
        "EMSC Seismic Portal FDSN events (min M2)",
        "Below network detection. Delayed.",
        host="www.seismicportal.eu",
    ),
    FeedSpec(
        "satnogs",
        "radio",
        "shipped",
        "SatNOGS Network ground-station pins",
        "Observer positions. No audio. Not a viewshed.",
        host="network.satnogs.org",
    ),
    FeedSpec(
        "metar",
        "weather",
        "shipped",
        "Aviation Weather Center METAR GeoJSON (last hour)",
        "Station reports. Not a forecast mesh.",
        host="aviationweather.gov",
    ),
    FeedSpec(
        "waqi",
        "weather",
        "keyed",
        "WAQI / AQICN station AQI (free token)",
        "WAQI + originating EPA. Local observer. Not a car. Not every city.",
        host="api.waqi.info",
        key="earth.waqi_token",
    ),
    FeedSpec(
        "ndbc",
        "weather",
        "shipped",
        "NOAA NDBC buoy / C-MAN catalog",
        "Published stations. Open ocean between buoys is a hole. Not a hull.",
        host="www.ndbc.noaa.gov",
    ),
    FeedSpec(
        "usgs-volcanoes",
        "sites",
        "shipped",
        "USGS volcano monitoring GeoJSON",
        "Monitored vents. Unmonitored volcanoes stay off.",
        host="volcanoes.usgs.gov",
    ),
    FeedSpec(
        "gdacs",
        "sites",
        "shipped",
        "GDACS humanitarian disaster events",
        "Named Orange/Red events. Not every local incident. Not a face.",
        host="www.gdacs.org",
    ),
    FeedSpec(
        "geonet",
        "quakes",
        "shipped",
        "GeoNet New Zealand quakes",
        "NZ network. Elsewhere stays empty.",
        host="api.geonet.org.nz",
    ),
    FeedSpec(
        "wzdx-ut",
        "traffic",
        "shipped",
        "Utah WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="udottraffic.utah.gov",
    ),
    FeedSpec(
        "wzdx-ky",
        "traffic",
        "shipped",
        "Kentucky WZDx work-zone GeoJSON (KYTC public bucket)",
        "Published closures. Individual cars are not a public feed.",
        host="storage.googleapis.com",
    ),
    FeedSpec(
        "wzdx-mo",
        "traffic",
        "shipped",
        "Missouri WZDx work-zone JSON",
        "Published closures. Individual cars are not a public feed.",
        host="traveler.modot.org",
    ),
    FeedSpec(
        "wzdx-wi",
        "traffic",
        "shipped",
        "Wisconsin WZDx (no-key path; CARS events want a key)",
        "Published closures. Individual cars are not a public feed.",
        host="511wi.gov",
    ),
    FeedSpec(
        "wzdx-id",
        "traffic",
        "shipped",
        "Idaho WZDx (no-key path; CARS events want a key)",
        "Published closures. Individual cars are not a public feed.",
        host="511.idaho.gov",
    ),
    FeedSpec(
        "md-chart",
        "traffic",
        "shipped",
        "Maryland CHART incidents GeoJSON",
        "MD roads. Individual cars are not a public feed.",
        host="chartimap1.sha.maryland.gov",
    ),
    FeedSpec(
        "sa-traffic",
        "traffic",
        "shipped",
        "South Australia traffic ArcGIS GeoJSON",
        "SA metro roads. Individual cars are not a public feed.",
        host="maps.sa.gov.au",
    ),
    FeedSpec(
        "wa-traffic",
        "traffic",
        "shipped",
        "Western Australia Main Roads travel GeoJSON",
        "WA roads. Individual cars are not a public feed.",
        host="gisservices.mainroads.wa.gov.au",
    ),
    FeedSpec(
        "sa-closures",
        "traffic",
        "shipped",
        "South Australia road closures and detours GeoJSON",
        "SA roads. Individual cars are not a public feed.",
        host="maps.sa.gov.au",
    ),
    FeedSpec(
        "wa-roadworks",
        "traffic",
        "shipped",
        "Main Roads WA roadworks GeoJSON",
        "WA roads. Individual cars are not a public feed.",
        host="gisservices.mainroads.wa.gov.au",
    ),
    FeedSpec(
        "wa-events",
        "traffic",
        "shipped",
        "Main Roads WA events-management GeoJSON",
        "WA roads. Individual cars are not a public feed.",
        host="gisservices.mainroads.wa.gov.au",
    ),
    FeedSpec(
        "nd-511",
        "traffic",
        "shipped",
        "North Dakota highway alerts GeoJSON",
        "ND roads. Individual cars are not a public feed.",
        host="travelfiles.dot.nd.gov",
    ),
    FeedSpec(
        "wzdx-az",
        "traffic",
        "shipped",
        "AZ511 WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="az511.gov",
    ),
    FeedSpec(
        "wzdx-la",
        "traffic",
        "shipped",
        "LADOTD WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="511la.org",
    ),
    FeedSpec(
        "wzdx-ia",
        "traffic",
        "shipped",
        "Iowa WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="511ia.org",
    ),
    FeedSpec(
        "wzdx-mn",
        "traffic",
        "shipped",
        "Minnesota WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="511mn.org",
    ),
    FeedSpec(
        "wzdx-ga",
        "traffic",
        "shipped",
        "Georgia WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="511ga.org",
    ),
    FeedSpec(
        "on-cameras",
        "cameras",
        "shipped",
        "Ontario 511 published camera positions",
        "Position only. No stills.",
        host="511on.ca",
    ),
    FeedSpec(
        "mb-cameras",
        "cameras",
        "shipped",
        "Manitoba 511 published camera positions",
        "Position only. No stills.",
        host="511.gov.mb.ca",
    ),
    FeedSpec(
        "ns-cameras",
        "cameras",
        "shipped",
        "Nova Scotia 511 published camera positions",
        "Position only. No stills.",
        host="511.novascotia.ca",
    ),
    FeedSpec(
        "ab-cameras",
        "cameras",
        "shipped",
        "Alberta 511 published camera positions",
        "Position only. No stills.",
        host="511.alberta.ca",
    ),
    FeedSpec(
        "sk-cameras",
        "cameras",
        "shipped",
        "Saskatchewan 511 published camera positions",
        "Position only. No stills.",
        host="hotline.gov.sk.ca",
    ),
    FeedSpec(
        "fl-cameras",
        "cameras",
        "shipped",
        "Florida 511 published camera positions",
        "Position only. No stills.",
        host="fl511.com",
    ),
    FeedSpec(
        "ny-cameras",
        "cameras",
        "shipped",
        "New York 511 published camera positions",
        "Position only. No stills.",
        host="511ny.org",
    ),
    FeedSpec(
        "co-cameras",
        "cameras",
        "shipped",
        "COtrip 511 published camera positions",
        "Position only. No stills.",
        host="www.cotrip.org",
    ),
    FeedSpec(
        "ia-cameras",
        "cameras",
        "shipped",
        "Iowa 511 published camera positions",
        "Position only. No stills.",
        host="511ia.org",
    ),
    FeedSpec(
        "mn-cameras",
        "cameras",
        "shipped",
        "Minnesota 511 published camera positions",
        "Position only. No stills.",
        host="511mn.org",
    ),
    FeedSpec(
        "ga-cameras",
        "cameras",
        "shipped",
        "Georgia 511 published camera positions",
        "Position only. No stills.",
        host="511ga.org",
    ),
    FeedSpec(
        "tripcheck",
        "cameras",
        "shipped",
        "ODOT TripCheck CCTV inventory",
        "Position only. No stills.",
        host="tripcheck.com",
    ),
    FeedSpec(
        "md-cameras",
        "cameras",
        "shipped",
        "SHA traffic-camera GeoJSON",
        "Position only. No stills.",
        host="mdgeodata.md.gov",
    ),
    FeedSpec(
        "nd-cameras",
        "cameras",
        "shipped",
        "NDDOT camera GeoJSON",
        "Position only. No stills.",
        host="travelfiles.dot.nd.gov",
    ),
    FeedSpec(
        "al-algo",
        "cameras",
        "shipped",
        "ALGO / ALDOT published camera catalog",
        "Position only. Official still/HLS on click when the JSON includes it.",
        host="api.algotraffic.com",
    ),
    FeedSpec(
        "de-deldot",
        "cameras",
        "shipped",
        "DelDOT published camera catalog",
        "Position only. Official HLS on click when the JSON includes it.",
        host="tmc.deldot.gov",
    ),
    FeedSpec(
        "nz-cameras",
        "cameras",
        "shipped",
        "Waka Kotahi / NZTA published camera catalog",
        "Position only. Official still on click when the JSON includes it.",
        host="www.journeys.nzta.govt.nz",
    ),
    FeedSpec(
        "qc-cameras",
        "cameras",
        "shipped",
        "Quebec 511 / MTMD camera locations",
        "Position only. Player HTML is not look-from.",
        host="ws.mapserver.transports.gouv.qc.ca",
    ),
    FeedSpec(
        "qc-events",
        "traffic",
        "shipped",
        "Quebec 511 / MTMD road events",
        "Quebec roads. Individual cars are not a public feed.",
        host="ws.mapserver.transports.gouv.qc.ca",
    ),
    FeedSpec(
        "de-autobahn",
        "traffic",
        "shipped",
        "Autobahn GmbH roadworks and warnings",
        "German autobahn. Individual cars are not a public feed.",
        host="verkehr.autobahn.de",
    ),
    FeedSpec(
        "wzdx-nc",
        "traffic",
        "shipped",
        "NCDOT WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="drivenc.gov",
    ),
    FeedSpec(
        "wzdx-in",
        "traffic",
        "shipped",
        "Indiana WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="in.carsprogram.org",
    ),
    FeedSpec(
        "wzdx-ks",
        "traffic",
        "shipped",
        "Kansas WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="kscars.kandrive.gov",
    ),
    FeedSpec(
        "wzdx-wa",
        "traffic",
        "shipped",
        "WSDOT WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="wzdx.wsdot.wa.gov",
    ),
    FeedSpec(
        "wzdx-nb",
        "traffic",
        "shipped",
        "New Brunswick 511 WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="511.gnb.ca",
    ),
    FeedSpec(
        "wzdx-pe",
        "traffic",
        "shipped",
        "PEI 511 WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="511.gov.pe.ca",
    ),
    FeedSpec(
        "wzdx-yt",
        "traffic",
        "shipped",
        "Yukon 511 WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="511yukon.ca",
    ),
    FeedSpec(
        "wzdx-ak",
        "traffic",
        "shipped",
        "Alaska 511 WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="511.alaska.gov",
    ),
    FeedSpec(
        "wzdx-nv",
        "traffic",
        "shipped",
        "Nevada WZDx work-zone GeoJSON",
        "Published closures. Individual cars are not a public feed.",
        host="nvroads.com",
    ),
    FeedSpec(
        "coops",
        "weather",
        "shipped",
        "NOAA CO-OPS tide-prediction stations",
        "Published gauges. Open ocean is a hole. Not a hull.",
        host="api.tidesandcurrents.noaa.gov",
    ),
    FeedSpec(
        "ioc-sealevel",
        "weather",
        "shipped",
        "IOC-UNESCO sea-level station list",
        "Published gauges. Not altimetry everywhere.",
        host="www.ioc-sealevelmonitoring.org",
    ),
    FeedSpec(
        "argo",
        "sites",
        "shipped",
        "IFREMER Argo last-fix sample (ERDDAP)",
        "Sample of recent surfacings, not a painted shell.",
        host="erddap.ifremer.fr",
    ),
    FeedSpec(
        "ingv-stations",
        "sites",
        "shipped",
        "INGV FDSN station text (IV network)",
        "Published seismometer sites. Not every quake.",
        host="webservices.ingv.it",
    ),
    FeedSpec(
        "geofon-stations",
        "sites",
        "shipped",
        "GFZ GEOFON FDSN station text (GE network)",
        "Published seismometer sites. Not every quake.",
        host="geofon.gfz-potsdam.de",
    ),
    FeedSpec(
        "iris-iu",
        "sites",
        "shipped",
        "IRIS FDSN station text (IU global network)",
        "Published seismometer sites. Not every quake.",
        host="service.iris.edu",
    ),
    FeedSpec(
        "nrcan-stations",
        "sites",
        "shipped",
        "NRCAN FDSN station text (CN network)",
        "Published seismometer sites. Not every quake.",
        host="www.earthquakescanada.nrcan.gc.ca",
    ),
    FeedSpec(
        "geonet-stations",
        "sites",
        "shipped",
        "GeoNet FDSN station text (NZ network)",
        "Published seismometer sites. Not every quake.",
        host="service.geonet.org.nz",
    ),
    FeedSpec(
        "mo-cameras",
        "cameras",
        "shipped",
        "MoDOT published camera catalog",
        "Position only. Official still/stream on click when the JSON includes it.",
        host="mapping.modot.mo.gov",
    ),
    FeedSpec(
        "qc-chantiers",
        "traffic",
        "shipped",
        "Quebec 511 / MTMD construction GeoJSON",
        "Quebec roads. Individual cars are not a public feed.",
        host="ws.mapserver.transports.gouv.qc.ca",
    ),
    FeedSpec(
        "qc-conditions",
        "traffic",
        "shipped",
        "Quebec 511 / MTMD road-condition GeoJSON",
        "Quebec roads. Individual cars are not a public feed.",
        host="ws.mapserver.transports.gouv.qc.ca",
    ),
    FeedSpec(
        "fi-rwis",
        "weather",
        "shipped",
        "Fintraffic road-weather stations",
        "Published sensors. Not a forecast mesh.",
        host="tie.digitraffic.fi",
    ),
    FeedSpec(
        "lt-rwis",
        "weather",
        "shipped",
        "Lithuania eismoinfo road-weather stations",
        "Published sensors. Not a forecast mesh.",
        host="eismoinfo.lt",
    ),
    FeedSpec(
        "qc-rwis",
        "weather",
        "shipped",
        "Quebec 511 road-weather stations",
        "Published sensors. Not a forecast mesh.",
        host="ws.mapserver.transports.gouv.qc.ca",
    ),
    FeedSpec(
        "tx-drivetexas",
        "traffic",
        "keyed",
        "DriveTexas / TxDOT highway conditions + WZDx (free key; no cameras in this API)",
        "Texas state highways. Individual cars are not a public feed. This feed has no CCTV.",
        host="api.drivetexas.org",
        key="earth.drivetexas_key",
    ),
    FeedSpec(
        "nsw-cameras",
        "cameras",
        "keyed",
        "NSW Live Traffic camera GeoJSON (Open Data API key)",
        "Position plus official still when href is a JPEG. Header Authorization: apikey TOKEN.",
        host="api.transport.nsw.gov.au",
        key="earth.nsw_key",
    ),
    FeedSpec(
        "wa-wsdot-cameras",
        "cameras",
        "keyed",
        "WSDOT highway cameras (AccessCode)",
        "Position plus official still when ImageURL is on images.wsdot.wa.gov.",
        host="wsdot.wa.gov",
        key="earth.wsdot_access_code",
    ),
    FeedSpec(
        "wa-wsdot-alerts",
        "traffic",
        "keyed",
        "WSDOT highway alerts (AccessCode)",
        "Published incidents. Individual cars are not a public feed.",
        host="wsdot.wa.gov",
        key="earth.wsdot_access_code",
    ),
    FeedSpec(
        "oh-ohgo-cameras",
        "cameras",
        "keyed",
        "OHGO / ODOT cameras (developer key)",
        "Position plus official still when LargeUrl/SmallUrl is on itscameras.dot.state.oh.us.",
        host="publicapi.ohgo.com",
        key="earth.ohgo_key",
    ),
    FeedSpec(
        "oh-ohgo-events",
        "traffic",
        "keyed",
        "OH 511 incidents + construction (developer key)",
        "Published incidents. Individual cars are not a public feed.",
        host="publicapi.ohgo.com",
        key="earth.ohgo_key",
    ),
    FeedSpec(
        "nc-drivenc-cameras",
        "cameras",
        "keyed",
        "DriveNC / NCDOT cameras (developer key). WZDx already ships no-key.",
        "Position plus official still when the CARS JSON includes it.",
        host="drivenc.gov",
        key="earth.drivenc_key",
    ),
    FeedSpec(
        "cars-ut",
        "cameras",
        "keyed",
        "UDOT Travel-IQ cameras + events (developer key). WZDx already ships no-key.",
        "CARS ?key=. Individual cars are not a public feed.",
        host="udottraffic.utah.gov",
        key="earth.cars_keys",
    ),
    FeedSpec(
        "cars-az",
        "cameras",
        "keyed",
        "AZ511 Travel-IQ cameras + events (developer key). WZDx already ships no-key.",
        "CARS ?key=. Individual cars are not a public feed.",
        host="az511.gov",
        key="earth.cars_keys",
    ),
    FeedSpec(
        "cars-id",
        "cameras",
        "keyed",
        "ITD Travel-IQ cameras + events (developer key). WZDx already ships no-key.",
        "CARS ?key=. Individual cars are not a public feed.",
        host="511.idaho.gov",
        key="earth.cars_keys",
    ),
    FeedSpec(
        "cars-wi",
        "cameras",
        "keyed",
        "WisDOT Travel-IQ cameras + events (developer key). WZDx already ships no-key.",
        "CARS ?key=. Individual cars are not a public feed.",
        host="511wi.gov",
        key="earth.cars_keys",
    ),
    FeedSpec(
        "cars-la",
        "cameras",
        "keyed",
        "LADOTD Travel-IQ cameras + events (developer key). WZDx already ships no-key.",
        "CARS ?key=. Individual cars are not a public feed.",
        host="511la.org",
        key="earth.cars_keys",
    ),
    FeedSpec(
        "cars-ak",
        "cameras",
        "keyed",
        "Alaska 511 Travel-IQ cameras + events (developer key). WZDx already ships no-key.",
        "CARS ?key=. Individual cars are not a public feed.",
        host="511.alaska.gov",
        key="earth.cars_keys",
    ),
    FeedSpec(
        "cars-nv",
        "cameras",
        "keyed",
        "Nevada 511 Travel-IQ cameras + events (developer key). WZDx already ships no-key.",
        "CARS ?key=. Individual cars are not a public feed.",
        host="nvroads.com",
        key="earth.cars_keys",
    ),
    FeedSpec(
        "cars-ct",
        "cameras",
        "keyed",
        "CTDOT Travel-IQ cameras + events (developer key)",
        "CARS ?key=. Individual cars are not a public feed.",
        host="ctroads.org",
        key="earth.cars_keys",
    ),
    FeedSpec(
        "cars-ne",
        "cameras",
        "keyed",
        "Nebraska 511 Travel-IQ cameras + events (developer key)",
        "CARS ?key=. Individual cars are not a public feed.",
        host="511.nebraska.gov",
        key="earth.cars_keys",
    ),
    FeedSpec(
        "openaq",
        "weather",
        "keyed",
        "OpenAQ v3 station locations (free key)",
        "OpenAQ + originating provider. Local observer. Overlaps WAQI. Not a car.",
        host="api.openaq.org",
        key="earth.openaq_key",
    ),
    FeedSpec(
        "earthdata",
        "radar",
        "later",
        "NASA Earthdata login for Sentinel-1 GRD later (free account)",
        "Catalog footprints already ship via ASF. Scene download is later.",
    ),
    FeedSpec(
        "copernicus-dataspace",
        "radar",
        "later",
        "Copernicus Data Space (free account) for extra Sentinel later",
        "Not sat-AIS. A scene is not a hull.",
    ),
    FeedSpec(
        "shodan-banners",
        "cameras",
        "keyed",
        "Shodan banner catalog if a free key already exists",
        "IP and banner text. Not a login and not look-from. An open port is not consent.",
        host="api.shodan.io",
        key="earth.shodan_key",
    ),
    FeedSpec(
        "owned-rtsp",
        "cameras",
        "shipped",
        "Operator-owned RTSP / local webcam live look-from and ENU face boxes",
        "Only cameras we own. Click plays the stream you pasted. "
        "URL never stored. No global face index.",
    ),
    FeedSpec(
        "contacts",
        "people",
        "shipped",
        "Address-book people with lat/lon on the card",
        "Unknown people stay off the map. Never geocoded.",
    ),
    FeedSpec(
        "unsecured-cams",
        "cameras",
        "out",
        "Insecam / default-password / anyone's open RTSP",
        "An open port is not consent.",
    ),
    FeedSpec(
        "face-index",
        "sites",
        "out",
        "Global face search on municipal CCTV",
        "Named public search is events and assets, not faces.",
    ),
    FeedSpec(
        "car-vin",
        "traffic",
        "out",
        "Every car / plate / phone ping",
        "There is no legal global car tracker. Observer of broadcasts, not a dragnet.",
    ),
)

FEED_BY_ID: dict[str, FeedSpec] = {spec.id: spec for spec in FEEDS}


def shipped_hosts() -> tuple[str, ...]:
    return tuple(spec.host for spec in FEEDS if spec.status == "shipped" and spec.host)
