"""Test-matrix item definitions for scripts/live_matrix.py (new file, ASCII only).

Single source of truth: matrix.md is generated from this list and the runner
scores against it. Workspace root during the run is outputs/test_matrix, so
prompts use paths such as work/sales.csv.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field

# Never called, never registered during the run. Touching one hard-fails the run.
BANNED = frozenset(
    {
        "send_sms",
        "send_email",
        "inbox",
        "inbound_sms",
        "schedule",
        "agenda",
        "contacts",
        "camera",
        "clipboard",
        "desktop",
    }
)


@dataclass
class Item:
    id: str
    kind: str  # single | chain | regress | slash
    tool: str
    prompts: list
    tools: list = field(default_factory=list)  # ordered; each entry = tuple of alternatives
    ans_all: tuple = ()
    ans_any: tuple = ()
    files: list = field(default_factory=list)  # (suffix, needle) -> new file with that text
    db: list = field(default_factory=list)  # (table, column, needle) in isolated memory.db
    timeout: int = 300
    notes: str = ""
    skip: str = ""
    no_tools_ok: bool = False
    # --- additive scoring fields (all default to "not checked") ---
    ans_none: tuple = ()  # substrings that must NOT appear in the final answer
    gate: tuple = ()  # "tool" or "tool:action" that MUST raise a confirm card
    decline: tuple = ()  # "tool" or "tool:action" the runner answers "skip" to
    keep: tuple = ()  # paths (relative to outputs/test_matrix) that must exist after
    gone: tuple = ()  # paths (relative to outputs/test_matrix) that must not exist after
    live_sends: int = 0  # real provider sends this item may cause (comms items only)
    recipients: tuple = ()  # allowed recipient aliases/addresses (comms items only)


# Refusal phrases that must never stand in for a real answer. Items opt in with
# ans_none=IDK so existing items keep their old scoring.
IDK = (
    "i don't know",
    "i do not know",
    "i'm not sure",
    "i am not sure",
    "i cannot",
    "i can't",
    "unable to",
    "no information",
)


def _t(*names):
    return [(n,) if isinstance(n, str) else tuple(n) for n in names]


def S(
    id,
    tool,
    prompt,
    tools,
    all=(),
    any=(),
    files=(),
    db=(),
    timeout=300,
    notes="",
    kind="single",
    skip="",
    no_tools_ok=False,
    ans_none=(),
    gate=(),
    decline=(),
    keep=(),
    gone=(),
    live_sends=0,
    recipients=(),
):
    prompts = prompt if isinstance(prompt, list) else [prompt]
    return Item(
        id,
        kind,
        tool,
        prompts,
        _t(*tools),
        tuple(all),
        tuple(any),
        list(files),
        list(db),
        timeout,
        notes,
        skip,
        no_tools_ok,
        tuple(ans_none),
        tuple(gate),
        tuple(decline),
        tuple(keep),
        tuple(gone),
        live_sends,
        tuple(recipients),
    )


def C(id, tool, prompt, tools, all=(), any=(), files=(), db=(), timeout=480, notes="", **extra):
    return S(id, tool, prompt, tools, all, any, files, db, timeout, notes, kind="chain", **extra)


ITEMS = [
    # ---------------- singles: one tool each ----------------
    S("S01_calculator_pct", "calculator", "What is 12.5% of 640?", ["calculator"], all=["80"]),
    S(
        "S02_calculator_exact",
        "calculator",
        "Compute 1234.56 * 7.25 exactly.",
        ["calculator"],
        all=["8950.56"],
    ),
    S("S03_cas_diff", "cas", "Differentiate x^3 * log(x) with respect to x.", ["cas"], all=["log"]),
    S("S04_cas_solve", "cas", "Solve x^2 - 5x + 6 = 0 for x.", ["cas"], all=["2", "3"]),
    S("S05_cas_integrate", "cas", "Integrate x^2 from 0 to 3.", ["cas"], all=["9"]),
    S("S06_units_ftin", "units", "Convert 5 ft 8 in to meters.", ["units"], any=["1.727", "1.73"]),
    S(
        "S07_units_constant",
        "units",
        "What is the speed of light in m/s?",
        ["units"],
        any=["299792458", "299,792,458", "2.998"],
    ),
    S(
        "R01_units_f_to_c",
        "units",
        "Convert 90 degrees Fahrenheit to Celsius.",
        [("units", "calculator")],
        all=["32.2"],
        kind="regress",
        notes="Known failure: units refusal sentence about CODATA instead of 32.2.",
    ),
    S(
        "S08_units_kmh_mph",
        "units",
        "Convert 100 kilometers per hour to miles per hour.",
        [("units", "calculator")],
        all=["62.1"],
    ),
    S(
        "S09_python_fib",
        "python",
        "Using python, print the 12th Fibonacci number. Use F1=1, F2=1.",
        [("python", "cas")],
        all=["144"],
    ),
    S(
        "S10_python_sqrt",
        "python",
        "Using python, print the square root of 2 to at least 8 decimal places.",
        [("python", "calculator")],
        all=["1.41421356"],
    ),
    S(
        "S11_python_sumsq",
        "python",
        "Using python, compute the sum of the squares of the integers 1 through 20.",
        [("python", "calculator")],
        all=["2870"],
    ),
    S(
        "S12_web_search",
        "web_search",
        "Search the web for the official Python programming language website and give me its URL.",
        ["web_search"],
        all=["python.org"],
    ),
    S(
        "S13_scrape",
        "scrape",
        "Scrape https://en.wikipedia.org/wiki/Ada_Lovelace and tell me what year she was born.",
        ["scrape"],
        all=["1815"],
    ),
    S(
        "S14_web_fetch",
        "web_fetch",
        "Use web_fetch on https://example.com and tell me the title of the page.",
        ["web_fetch"],
        all=["example domain"],
    ),
    S(
        "S15_research_report",
        "research_report",
        "Write a sourced research report on how lithium iron phosphate batteries differ from NMC batteries.",
        ["research_report"],
        files=[(".md", "lithium")],
        timeout=1000,
        notes="Slow: 5-12 min on the 9B.",
    ),
    S(
        "S16_weather",
        "weather",
        "What's the weather forecast for Springfield, Illinois today?",
        ["weather"],
        any=["high", "low", "springfield"],
    ),
    S(
        "S17_user_location",
        "user_location",
        "What city is my profile location set to? Use your location tool.",
        ["user_location"],
        all=["springfield"],
        notes="Synthetic profile (Springfield) in the isolated data dir.",
    ),
    S(
        "S18_memory",
        "memory",
        ["Remember that my favorite color is teal.", "What do you remember about me?"],
        ["memory"],
        all=["teal"],
        notes="Two prompts: remember, then list.",
    ),
    S(
        "S19_recall",
        "recall",
        [
            "My cat is named Biscuit and she loves tuna.",
            "@clear",
            "Use recall to search our past conversations and tell me my cat's name.",
        ],
        ["recall"],
        all=["biscuit"],
        notes="Working memory cleared between prompts; archive must supply it.",
    ),
    S(
        "S20_tasks",
        "tasks",
        ["Add a task: renew the library card, due 2026-10-15.", "List my open tasks."],
        ["tasks"],
        all=["library"],
        db=[("tasks", "title", "library")],
    ),
    S(
        "S21_goals",
        "goals",
        ["Add a goal: run a half marathon by next spring.", "List my goals."],
        ["goals"],
        all=["marathon"],
        db=[("goals", "title", "marathon")],
    ),
    S(
        "S22_notes",
        "notes",
        "Add a note titled Matrix Note with the text: alpha bravo charlie.",
        [("notes", "workspace")],
        files=[(".md", "alpha bravo")],
    ),
    S(
        "S23_workspace_write",
        "workspace",
        "Write a file work/hello.txt containing exactly: hello matrix",
        ["workspace"],
        files=[(".txt", "hello matrix")],
    ),
    S(
        "S24_workspace_list",
        "workspace",
        "List the files in the work folder.",
        ["workspace"],
        all=["sales.csv"],
    ),
    S(
        "S25_workspace_read",
        "workspace",
        "Read the file work/hello_script.py and tell me what it prints.",
        ["workspace"],
        all=["4242"],
    ),
    S(
        "S26_analyze",
        "analyze",
        "Using analyze, how many rows are in work/sales.csv and what is the total of the revenue column?",
        ["analyze"],
        all=["750"],
    ),
    S(
        "S27_sql",
        "sql",
        "Using the sql tool on work/sales.csv, what is the maximum revenue?",
        ["sql"],
        all=["250"],
    ),
    S(
        "S28_plot_expr",
        "plot",
        "Plot a line chart of sin(x) for x from 0 to 6.28.",
        ["plot"],
        files=[(".png", "")],
    ),
    S(
        "S29_plot_csv",
        "plot",
        "Draw a bar chart from work/sales.csv with the region column as categories and revenue as values.",
        ["plot"],
        files=[(".png", "")],
    ),
    S(
        "S30_doc_md",
        "document",
        "Create a markdown document titled Matrix Doc Md with a one-paragraph body about testing software.",
        ["document"],
        files=[(".md", "test")],
    ),
    S(
        "S31_doc_pdf",
        "document",
        "Create a PDF document titled Matrix Doc Pdf whose body says: pdf marker 5150.",
        ["document"],
        files=[(".pdf", "5150")],
    ),
    S(
        "S32_doc_docx",
        "document",
        "Create a Word document titled Matrix Doc Docx whose body says: docx marker 6262.",
        ["document"],
        files=[(".docx", "6262")],
    ),
    S(
        "S33_doc_csv",
        "document",
        "Create a CSV document titled Matrix Doc Csv with header name,score and rows ann,90 and bo,85.",
        ["document"],
        files=[(".csv", "ann")],
    ),
    S(
        "S34_doc_xlsx",
        "document",
        "Create an Excel spreadsheet titled Matrix Doc Xlsx with header item,qty and rows apple,3 and pear,7.",
        ["document"],
        files=[(".xlsx", "pear")],
    ),
    S(
        "S35_doc_txt",
        "document",
        "Create a plain text document titled Matrix Doc Txt whose body says: txt marker 7373.",
        ["document"],
        files=[(".txt", "7373")],
    ),
    S(
        "S36_pdf_merge",
        "pdf",
        "Merge work/a.pdf and work/b.pdf into one PDF.",
        ["pdf"],
        files=[(".pdf", "alpha-123"), (".pdf", "bravo-456")],
    ),
    S(
        "S37_doc_extract_docx",
        "doc_extract",
        "Extract the text of work/memo.docx and tell me the project codename.",
        ["doc_extract"],
        all=["falcon-77"],
    ),
    S(
        "S38_doc_extract_pdf",
        "doc_extract",
        "Extract the text of work/a.pdf and tell me the code written on it.",
        ["doc_extract"],
        all=["alpha-123"],
    ),
    S(
        "S39_ocr",
        "ocr",
        "Use OCR on work/invoice.png and tell me the amount due.",
        ["ocr"],
        all=["1250"],
    ),
    S(
        "S40_vision",
        "vision",
        "Look at work/shapes.png and tell me what color the circle is.",
        ["vision"],
        all=["red"],
        timeout=420,
    ),
    S(
        "S41_image_edit",
        "image_edit",
        "Convert work/shapes.png to grayscale.",
        ["image_edit"],
        files=[(".png", "")],
    ),
    S(
        "S42_git_info",
        "git_info",
        "Show me the last 2 git commits.",
        ["git_info"],
        any=["silent excepts", "merge remote-tracking", "unfinished refactor", "commit"],
    ),
    S(
        "S43_run_script",
        "run_script",
        "Run the script work/hello_script.py and tell me what it printed.",
        ["run_script"],
        all=["4242"],
    ),
    S(
        "S44_run_task",
        "run_task",
        "List the declared project tasks, then run the one called hello.",
        ["run_task"],
        all=["4242"],
    ),
    S(
        "S45_diagnostics",
        "diagnostics",
        "Run the diagnostics tool with target test_units_temp and report the result.",
        ["diagnostics"],
        any=["pass"],
        timeout=420,
    ),
    S(
        "S46_catalog_arxiv",
        "catalog",
        "Search arXiv for papers about 'attention is all you need' and list a couple of titles.",
        ["catalog"],
        any=["arxiv", "attention"],
    ),
    S(
        "S47_catalog_horizons",
        "catalog",
        "Use the catalog horizons lookup for Mars (target 499) on 2026-10-01, observer table, and report the RA and Dec.",
        ["catalog"],
        any=["ra", "right ascension", "dec"],
    ),
    S(
        "S48_watch",
        "watch",
        "Is the house watch quiet? What listeners are bound?",
        ["watch"],
        any=["quiet", "none", "no "],
    ),
    S(
        "S49_rooms",
        "rooms",
        "Create a room called Matrix Test Room with the purpose: verifying tools.",
        ["rooms"],
        any=["matrix test", "matrix-test"],
    ),
    S("S50_tile", "tile", "Open the history tile.", ["tile"], any=["history", "open"]),
    S(
        "S51_remind",
        "remind",
        "Remind me in 600 minutes to stretch.",
        ["remind"],
        any=["remind", "stretch"],
    ),
    S(
        "S52_solar_status",
        "solar",
        "What is the status of the solar system simulation?",
        ["solar"],
        any=["solar", "loaded", "simulation"],
    ),
    S(
        "S53_solar_load",
        "solar",
        "Load the solar system simulation with the solar tool.",
        ["solar"],
        any=["solar", "loaded", "horizons", "planets"],
        timeout=420,
    ),
    S(
        "S54_earth_status",
        "earth",
        "What is the status of the Earth view?",
        ["earth"],
        any=["earth", "solar"],
    ),
    S(
        "S55_browser_read",
        "browser",
        "Use the browser to open https://example.com and tell me the heading on the page.",
        ["browser"],
        all=["example domain"],
        timeout=420,
    ),
    S(
        "S56_browser_screenshot",
        "browser",
        "Use the browser to open https://example.com and take a screenshot of the page.",
        ["browser"],
        files=[(".png", "")],
        timeout=420,
    ),
    S(
        "S57_image_generate",
        "image",
        "Generate an image of a red balloon.",
        ["image"],
        skip="ComfyUI is not healthy at http://127.0.0.1:8188 (comfy_is_healthy False)",
    ),
    S(
        "S58_transcribe",
        "transcribe",
        "Transcribe the audio file work/clip.wav.",
        ["transcribe"],
        skip="needs the loaded STT voice engine; headless run has a cold ear and voice input is excluded",
    ),
    # ---------------- slash commands / features ----------------
    S(
        "X01_help",
        "/help",
        "/help",
        [],
        all=["slash commands"],
        kind="slash",
        no_tools_ok=True,
        timeout=60,
    ),
    S(
        "X02_tools",
        "/tools",
        "/tools",
        [],
        all=["calculator"],
        kind="slash",
        no_tools_ok=True,
        timeout=60,
    ),
    S(
        "X03_slash_web_fetch",
        "/web_fetch",
        "/web_fetch url=https://example.com",
        ["web_fetch"],
        all=["example domain"],
        kind="slash",
        timeout=120,
    ),
    S(
        "X04_slash_workspace",
        "/workspace",
        "/workspace action=list path=work",
        ["workspace"],
        all=["sales.csv"],
        kind="slash",
        timeout=120,
    ),
    S(
        "X05_slash_analyze",
        "/analyze",
        "/analyze path=work/sales.csv action=summary",
        ["analyze"],
        all=["revenue"],
        kind="slash",
        timeout=120,
    ),
    S(
        "X06_slash_web_search",
        "/web_search",
        "/web_search query=python programming language",
        ["web_search"],
        all=["python"],
        kind="slash",
        timeout=120,
    ),
    S(
        "X07_slash_scrape",
        "/scrape",
        "/scrape url=https://en.wikipedia.org/wiki/Ada_Lovelace",
        ["scrape"],
        all=["lovelace"],
        kind="slash",
        timeout=120,
    ),
    S(
        "X08_keep_note",
        "keep this:",
        "keep this: matrix keep marker 7421",
        [],
        files=[(".md", "7421")],
        kind="slash",
        no_tools_ok=True,
        timeout=120,
    ),
    S(
        "X09_rooms_list",
        "/rooms",
        "/rooms",
        [],
        any=["room"],
        kind="slash",
        no_tools_ok=True,
        timeout=60,
    ),
    S(
        "X10_role_research",
        "/role",
        ["/role research", "/role fast"],
        [],
        any=["research", "fast"],
        kind="slash",
        no_tools_ok=True,
        timeout=120,
        notes="Research mode chip toggle.",
    ),
    # ---------------- chains: 2-5 tools in order ----------------
    C(
        "C01_units_calc_memory",
        "units>calculator>memory",
        "Convert 5 miles to kilometers with the units tool, then multiply those kilometers by 3 with the calculator, then remember that result as my weekly run distance.",
        ["units", "calculator", "memory"],
        all=["24.1"],
    ),
    C(
        "C02_weather_document",
        "weather>document",
        "Get today's weather forecast for Springfield, Illinois, then save a one-paragraph summary of it as a markdown document titled Springfield Weather Brief.",
        ["weather", "document"],
        files=[(".md", "springfield")],
    ),
    C(
        "C03_python_plot_document",
        "python>plot>document",
        "Using python compute the squares of 1 through 8, then plot those squares as a line chart, then create a markdown document titled Squares Report that mentions the chart.",
        ["python", "plot", "document"],
        files=[(".png", ""), (".md", "square")],
    ),
    C(
        "C04_ocr_calculator",
        "ocr>calculator",
        "Read the text in work/invoice.png with OCR, then use the calculator to add 8% tax to the amount due and report the final amount.",
        ["ocr", "calculator"],
        all=["1350"],
    ),
    C(
        "C05_write_run_read",
        "workspace>run_script>workspace",
        "Write a Python script work/sq.py that prints the square of 12, run it with run_script, then read work/sq.py back and show me its contents.",
        ["workspace", "run_script", "workspace"],
        all=["144"],
        files=[(".py", "print")],
    ),
    C(
        "C06_search_scrape_document",
        "web_search>scrape>document",
        "Search the web for the Wikipedia article on the Rosetta Stone, scrape the top Wikipedia result, then create a markdown document titled Rosetta Notes with a three-sentence summary.",
        ["web_search", ("scrape", "web_fetch"), "document"],
        files=[(".md", "rosetta")],
    ),
    C(
        "C07_catalog_document",
        "catalog>document",
        "Search arXiv for 'graph neural networks' and write a markdown document titled GNN Papers listing the first three paper titles.",
        ["catalog", "document"],
        files=[(".md", "graph")],
    ),
    C(
        "C08_analyze_plot",
        "analyze>plot",
        "Using analyze, find total revenue per region in work/sales.csv, then plot a bar chart of revenue by region from work/sales.csv.",
        ["analyze", "plot"],
        files=[(".png", "")],
    ),
    C(
        "C09_analyze_xlsx",
        "analyze>document",
        "Use analyze to get total revenue per region from work/sales.csv, then create an Excel spreadsheet titled Region Totals with those totals.",
        ["analyze", "document"],
        files=[(".xlsx", "north")],
    ),
    C(
        "C10_md_to_pdf",
        "document>document",
        "Create a markdown document titled Conversion Source with the text 'convert me 8812'. Then convert that markdown file to PDF using the document tool with from_path.",
        ["document", "document"],
        files=[(".md", "8812"), (".pdf", "8812")],
    ),
    C(
        "C11_md_to_docx",
        "document>document",
        "Create a markdown document titled Conversion Docx Source with the text 'docx convert 9934'. Then convert that markdown file to a Word docx using the document tool with from_path.",
        ["document", "document"],
        files=[(".md", "9934"), (".docx", "9934")],
    ),
    C(
        "C12_docextract_calc",
        "doc_extract>calculator",
        "Extract the text of work/memo.docx; it contains a budget figure. Use the calculator to double that budget and tell me the result.",
        ["doc_extract", "calculator"],
        all=["9000"],
    ),
    C(
        "C13_docextract_document",
        "doc_extract>document",
        "Extract the text of work/a.pdf and then write it into a markdown document titled Extracted A.",
        ["doc_extract", "document"],
        files=[(".md", "alpha-123")],
    ),
    C(
        "C14_vision_document",
        "vision>document",
        "Look at work/shapes.png with vision, then save a short description of it in a markdown document titled Shape Description.",
        ["vision", "document"],
        files=[(".md", "circle")],
        timeout=600,
    ),
    C(
        "C15_imageedit_ocr",
        "image_edit>ocr",
        "Convert work/invoice.png to grayscale with image_edit, then OCR the new grayscale image and tell me the amount due.",
        ["image_edit", "ocr"],
        all=["1250"],
    ),
    C(
        "C16_goal_task_tasks",
        "goals>tasks>tasks",
        "Add a goal 'learn welding', then add a task 'buy welding gloves' due 2026-11-01, then list my tasks.",
        ["goals", "tasks"],
        all=["gloves"],
        db=[("tasks", "title", "gloves"), ("goals", "title", "welding")],
    ),
    C(
        "C17_research_pdf",
        "research_report>document",
        "Write a sourced research report on how solid-state batteries differ from lithium-ion batteries, then convert that report to a PDF with the document tool.",
        ["research_report", "document"],
        files=[(".md", "solid"), (".pdf", "")],
        timeout=1500,
        notes="Slowest item: research (5-12 min) plus conversion.",
    ),
    C(
        "C18_python_memory",
        "python>memory",
        "Using python compute 7 factorial, then remember the result as a fact.",
        ["python", "memory"],
        all=["5040"],
    ),
    C(
        "C19_write_analyze_plot",
        "workspace>analyze>plot",
        "Write work/mini.csv with header x,y and rows 1,2 then 2,4 then 3,6. Use analyze to sum the y column, then plot x versus y as a line chart.",
        ["workspace", "analyze", "plot"],
        all=["12"],
        files=[(".png", "")],
    ),
    C(
        "C20_cas_python_calc",
        "cas>python>calculator",
        "Differentiate x^3 with cas, evaluate that derivative at x=4 with python, then confirm the number with the calculator.",
        ["cas", "python", "calculator"],
        all=["48"],
    ),
    C(
        "C21_git_document",
        "git_info>document",
        "Show the last 3 git commits and save them in a markdown document titled Recent Commits.",
        ["git_info", "document"],
        files=[(".md", "")],
    ),
    C(
        "C22_weather_units",
        "weather>units",
        "Get today's forecast high for Springfield, Illinois with the weather tool, then convert that temperature to Celsius with the units tool.",
        ["weather", "units"],
        any=["celsius", "c)", "\u00b0c", " c"],
    ),
    C(
        "C23_notes_notes",
        "notes>notes",
        "Add a note titled Chain Note saying 'bravo 3141', then list my notes.",
        ["notes", "notes"],
        files=[(".md", "3141")],
    ),
    C(
        "C24_pdf_merge_extract",
        "pdf>doc_extract",
        "Merge work/a.pdf and work/b.pdf into one PDF, then extract the text of the merged PDF and tell me both codes on it.",
        ["pdf", "doc_extract"],
        all=["alpha-123", "bravo-456"],
    ),
    C(
        "C25_browser_document",
        "browser>document",
        "Open https://example.com in the browser, read the page, then save its heading into a text document titled Browser Capture.",
        ["browser", "document"],
        files=[("", "example domain")],
        timeout=600,
    ),
    # ---------------- workaround probes: same tool, reworded prompt (separates tool health from gate bugs) ----------------
    S(
        "S37b_doc_extract_docx_reworded",
        "doc_extract",
        "Read the content of work/memo.docx and tell me the project codename.",
        ["doc_extract"],
        all=["falcon-77"],
        notes="Probe: avoids the words 'extract the text' (SMS intent false positive).",
    ),
    S(
        "S38b_doc_extract_pdf_reworded",
        "doc_extract",
        "Read the content of work/a.pdf and tell me the code written on it.",
        ["doc_extract"],
        all=["alpha-123"],
        notes="Probe: avoids 'extract the text'.",
    ),
    S(
        "S52b_solar_state_reworded",
        "solar",
        "Is the solar system simulation loaded right now?",
        ["solar"],
        any=["solar", "loaded", "not loaded", "no solar"],
        notes="Probe: avoids the word 'status' (git gate false positive).",
    ),
    S(
        "S54b_earth_state_reworded",
        "earth",
        "Which Reality view are we in right now, solar or Earth?",
        ["earth"],
        any=["earth", "solar"],
        notes="Probe: avoids the word 'status'.",
    ),
    C(
        "C12b_docextract_calc_reworded",
        "doc_extract>calculator",
        "Read the content of work/memo.docx; it contains a budget figure. Use the calculator to double that budget and tell me the result.",
        ["doc_extract", "calculator"],
        all=["9000"],
        notes="Probe: avoids 'extract the text'.",
    ),
    C(
        "C24b_pdf_merge_read_reworded",
        "pdf>doc_extract",
        "Merge work/a.pdf and work/b.pdf into one PDF, then read the content of the merged PDF and tell me both codes on it.",
        ["pdf", "doc_extract"],
        all=["alpha-123", "bravo-456"],
        notes="Probe: avoids 'extract the text'.",
    ),
    # ---------------- explicit-wording probes (P*): prompt names the tool/action to separate model-choice failures from tool failures ----------------
    S(
        "P01_browser_read_explicit",
        "browser",
        "Open https://example.com with the browser tool, then call the browser tool again with action=read and tell me the page heading.",
        ["browser"],
        all=["example domain"],
        timeout=420,
        notes="Probe.",
    ),
    S(
        "P02_browser_shot_explicit",
        "browser",
        "Use the browser tool to open https://example.com, then call the browser tool with action=screenshot.",
        ["browser"],
        files=[(".png", "")],
        timeout=420,
        notes="Probe.",
    ),
    S(
        "P03_diagnostics_explicit",
        "diagnostics",
        "Call the diagnostics tool with target=tests/test_units_temp.py and report the pass count.",
        ["diagnostics"],
        any=["pass"],
        timeout=420,
        notes="Probe.",
    ),
    S(
        "P07_doc_extract_docx_explicit",
        "doc_extract",
        "Call doc_extract with path work/memo.docx and tell me the project codename.",
        ["doc_extract"],
        all=["falcon-77"],
        timeout=420,
        notes="Probe.",
    ),
    C(
        "P04_weather_units_explicit",
        "weather>units",
        "Call the weather tool for Springfield, Illinois. Then call the units tool (action=convert) to convert today's forecast high in degrees Fahrenheit to Celsius.",
        ["weather", "units"],
        any=["celsius", "c)", "\u00b0c", " c"],
        notes="Probe.",
    ),
    C(
        "P05_write_runscript_explicit",
        "workspace>run_script>workspace",
        "Use workspace action=write to create work/sq2.py containing exactly: print(12*12). Then call run_script on work/sq2.py. Then tell me the output.",
        ["workspace", "run_script"],
        all=["144"],
        files=[(".py", "print")],
        notes="Probe.",
    ),
    C(
        "P06_imageedit_ocr_explicit",
        "image_edit>ocr",
        "Call image_edit on work/invoice.png with grayscale. Then call ocr (action=text) on the new grayscale file it saved and tell me the amount due.",
        ["image_edit", "ocr"],
        all=["1250"],
        notes="Probe.",
    ),
    C(
        "P08_pdf_merge_extract_explicit",
        "pdf>doc_extract",
        "Use the pdf tool to merge work/a.pdf and work/b.pdf with dest=work/merged.pdf. Then call doc_extract on work/merged.pdf and give me both codes.",
        ["pdf", "doc_extract"],
        all=["alpha-123", "bravo-456"],
        notes="Probe.",
    ),
    C(
        "P09_weather_document_explicit",
        "weather>document",
        "Call the weather tool for Springfield, Illinois. Then call the document tool with format=md and title Springfield Weather Brief and a body summarizing the forecast.",
        ["weather", "document"],
        files=[(".md", "springfield")],
        notes="Probe.",
    ),
    C(
        "P10_units_calc_memory_explicit",
        "units>calculator>memory",
        "Call units to convert 5 miles to kilometers. Then call calculator to multiply the kilometers by 3. Then call memory with action=remember to store the result as my weekly run distance.",
        ["units", "calculator", "memory"],
        all=["24.1"],
        notes="Probe.",
    ),
    C(
        "P11_browser_document_explicit",
        "browser>document",
        "Open https://example.com with the browser tool and read it. Then call the document tool with format=txt and title Browser Capture and body containing the page heading.",
        ["browser", "document"],
        files=[(".txt", "example domain")],
        timeout=600,
        notes="Probe.",
    ),
    # ======================================================================
    # Coverage additions (audit 2026-10-02). Every item below uses only
    # fixtures that make_fixtures() creates, stays inside outputs/test_matrix,
    # and touches no BANNED tool. Items with decline=/gate= need the runner
    # support added alongside them (confirm policy per item).
    # ======================================================================
    # ---- cas: actions the matrix never reached (diff/solve/integrate only) ----
    S(
        "S59_cas_sum",
        "cas",
        "Use cas to compute the sum of k for k from 1 to 100.",
        ["cas"],
        all=["5050"],
    ),
    S(
        "S60_cas_limit",
        "cas",
        "Use cas to find the limit of (x^2 - 49)/(x - 7) as x approaches 7.",
        ["cas"],
        all=["14"],
    ),
    S(
        "S61_cas_expand",
        "cas",
        "Use cas to expand (x + 3)^4.",
        ["cas"],
        all=["108", "54", "81"],
    ),
    S(
        "S62_cas_series",
        "cas",
        "Use cas to give the Taylor series of sin(x) around 0 up to order 6.",
        ["cas"],
        all=["120"],
        notes="x - x^3/6 + x^5/120.",
    ),
    S(
        "S63_cas_dsolve",
        "cas",
        "Use cas to solve the differential equation y'' + y = 0.",
        ["cas"],
        all=["sin", "cos"],
    ),
    S(
        "S64_cas_factor",
        "cas",
        "Use cas to factor x^2 + 7x + 12.",
        ["cas"],
        any=[
            "(x + 3)*(x + 4)",
            "(x + 4)*(x + 3)",
            "(x + 3)(x + 4)",
            "(x + 4)(x + 3)",
            "(x+3)(x+4)",
            "(x+4)(x+3)",
        ],
    ),
    S(
        "S65_cas_simplify",
        "cas",
        "Use cas to simplify (x^2 - 1)/(x - 1).",
        ["cas"],
        any=["x + 1", "x+1"],
        ans_none=IDK,
    ),
    # ---- analyze: query / head / describe ----
    S(
        "S66_analyze_query",
        "analyze",
        "Using analyze with action query, what is the mean revenue where region is north in work/sales.csv?",
        ["analyze"],
        all=["125"],
        ans_none=IDK,
        notes="north rows are 100 and 150.",
    ),
    S(
        "S67_analyze_head",
        "analyze",
        "Using analyze with action head, show the first 2 rows of work/sales.csv.",
        ["analyze"],
        all=["north", "150"],
        ans_none=IDK,
    ),
    S(
        "S68_analyze_describe",
        "analyze",
        "Using analyze with action describe on work/sales.csv, what is the standard deviation of revenue?",
        ["analyze"],
        any=["61.2", "54.7"],
        ans_none=IDK,
        notes="Sample std 61.24, population std 54.77.",
    ),
    # ---- memory: prefer / decide / episode (matrix only did remember + list) ----
    S(
        "S69_memory_prefer",
        "memory",
        "Store a preference: my editor theme is solarized dark.",
        ["memory"],
        db=[("preferences", "value", "solarized")],
    ),
    S(
        "S70_memory_decide",
        "memory",
        "Record a decision for the project Arelis: we keep local state in sqlite.",
        ["memory"],
        db=[("decisions", "text", "sqlite")],
    ),
    S(
        "S71_memory_episode",
        "memory",
        "Save an episode summary: finished the matrix audit on October 2.",
        ["memory"],
        db=[("episodes", "summary", "matrix audit")],
    ),
    # ---- pdf: rotate (merge was the only action) ----
    S(
        "S72_pdf_rotate",
        "pdf",
        "Rotate work/a.pdf by 90 degrees and save it as work/a_rot.pdf.",
        ["pdf"],
        files=[(".pdf", "alpha-123")],
        keep=("work/a_rot.pdf",),
    ),
    # ---- plot: scatter / histogram / residuals (line and bar only so far) ----
    S(
        "S73_plot_scatter",
        "plot",
        "Make a scatter plot with xs 1,2,3,4 and ys 2,4,5,9 titled Scatter Probe.",
        ["plot"],
        files=[(".png", "")],
        ans_none=IDK,
    ),
    S(
        "S74_plot_histogram",
        "plot",
        "Plot a histogram of the revenue column in work/sales.csv.",
        ["plot"],
        files=[(".png", "")],
        ans_none=IDK,
    ),
    S(
        "S75_plot_residuals",
        "plot",
        "Fit a straight line to xs 1,2,3,4,5 and ys 2,4,5,4,5 with the plot tool and plot the residuals. Tell me the fitted line.",
        ["plot"],
        all=["0.6", "2.2"],
        files=[(".png", "")],
        ans_none=IDK,
        notes="Least squares y = 0.6 x + 2.2.",
    ),
    # ---- browser: snapshot / tabs / pdf (open, read, screenshot only so far) ----
    S(
        "P12_browser_snapshot_explicit",
        "browser",
        "Open https://example.com with the browser tool, then call the browser tool with action=snapshot and tell me the page heading.",
        ["browser"],
        all=["example domain"],
        timeout=420,
        notes="Probe.",
    ),
    S(
        "P13_browser_tabs_explicit",
        "browser",
        "Open https://example.com with the browser tool, then call the browser tool with action=tabs and tell me the title of the open tab.",
        ["browser"],
        all=["example domain"],
        timeout=420,
        notes="Probe.",
    ),
    S(
        "P14_browser_pdf_explicit",
        "browser",
        "Open https://example.com with the browser tool, then call the browser tool with action=pdf to save the page as a PDF.",
        ["browser"],
        files=[(".pdf", "example domain")],
        timeout=420,
        notes="Probe. Verify the pdf lands under outputs/test_matrix on a dry run.",
    ),
    # ---- slash: deterministic tool-direct checks (no model choice involved) ----
    S(
        "X11_slash_workspace_grep",
        "/workspace",
        "/workspace action=grep query=4242 glob=*.py",
        ["workspace"],
        all=["hello_script.py"],
        kind="slash",
        timeout=120,
    ),
    S(
        "X12_slash_workspace_find",
        "/workspace",
        "/workspace action=find query=sales",
        ["workspace"],
        all=["sales.csv"],
        kind="slash",
        timeout=120,
    ),
    S(
        "X13_slash_workspace_write_copy_move_read",
        "/workspace",
        [
            "/workspace action=write path=work/slash_a.txt content=slash_7788",
            "/workspace action=copy path=work/slash_a.txt to=work/slash_b.txt",
            "/workspace action=move path=work/slash_b.txt to=work/slash_c.txt",
            "/workspace action=read path=work/slash_c.txt",
        ],
        ["workspace", "workspace", "workspace", "workspace"],
        all=["slash_7788"],
        keep=("work/slash_a.txt", "work/slash_c.txt"),
        gone=("work/slash_b.txt",),
        kind="slash",
        timeout=240,
        notes="Slash skips the confirm card by design; this checks the tool, not the gate.",
    ),
    S(
        "X14_slash_analyze_head",
        "/analyze",
        "/analyze path=work/sales.csv action=head",
        ["analyze"],
        all=["north", "revenue"],
        kind="slash",
        timeout=120,
    ),
    # ---- chains: stateful actions ----
    C(
        "C26_pdf_merge_split_read",
        "pdf>pdf>doc_extract",
        "Merge work/a.pdf and work/b.pdf into work/m2.pdf, then split page 2 of work/m2.pdf into work/p2.pdf, then read work/p2.pdf and tell me the code on it.",
        ["pdf", "pdf", "doc_extract"],
        all=["bravo-456"],
        ans_none=["alpha-123"],
        keep=("work/m2.pdf", "work/p2.pdf"),
        notes="'read' (not 'extract the text') avoids the SMS-intent false positive.",
    ),
    C(
        "C27_notes_add_search_read",
        "notes>notes",
        "Add a note titled Search Probe saying 'zulu 5577', then search my notes for 'zulu' and tell me the title of the matching note.",
        ["notes", "notes"],
        all=["search probe"],
        files=[(".md", "5577")],
    ),
    C(
        "C28_goal_lifecycle",
        "goals>goals>goals>goals",
        "Add a goal 'read ten books', pause that goal, resume it, then mark it done.",
        ["goals", "goals", "goals", "goals"],
        db=[("goals", "status", "done")],
    ),
    C(
        "C29_task_lifecycle",
        "tasks>tasks>tasks",
        "Add a task 'file expense report', mark it done, then list my done tasks.",
        ["tasks", "tasks", "tasks"],
        all=["expense report"],
        db=[("tasks", "status", "done")],
    ),
    C(
        "C30_rooms_create_update_get",
        "rooms>rooms>rooms",
        "Create a room called Matrix Probe Room with purpose: initial. Then update its purpose to 'zeta purpose 6620'. Then get the room and tell me its purpose.",
        ["rooms", "rooms", "rooms"],
        all=["zeta purpose 6620"],
    ),
    C(
        "C31_remind_list_cancel",
        "remind>remind>remind",
        "Remind me in 700 minutes to hydrate, then list my pending reminders, then cancel that reminder.",
        ["remind", "remind", "remind"],
        all=["hydrate"],
        gate=("remind:cancel",),
        notes="Cancel is a delete-class action, so it must raise a confirm card even when asked.",
    ),
    # ---- gate probes (G*): the confirm card must fire, and a decline must stick ----
    S(
        "G01_workspace_delete_declined",
        "workspace",
        "Delete the file work/scratch_decline.txt.",
        [],
        gate=("workspace:delete",),
        decline=("workspace:delete",),
        keep=("work/scratch_decline.txt",),
        no_tools_ok=True,
        notes="Runner answers skip to the card; the file must survive.",
    ),
    S(
        "G02_workspace_delete_allowed",
        "workspace",
        "Delete the file work/scratch_allow.txt.",
        ["workspace"],
        gate=("workspace:delete",),
        gone=("work/scratch_allow.txt",),
        notes="Control for G01: same card, allowed, file is gone.",
    ),
    S(
        "G03_run_script_declined",
        "run_script",
        "Run the script work/hello_script.py and tell me what it printed.",
        [],
        gate=("run_script",),
        decline=("run_script",),
        ans_none=["4242"],
        no_tools_ok=True,
        notes="run_script always pauses; a declined run must not print 4242.",
    ),
    S(
        "G04_memory_forget_declined",
        "memory",
        ["Remember that my locker number is 4471.", "Forget that my locker number is 4471."],
        ["memory"],
        gate=("memory:forget",),
        decline=("memory:forget",),
        db=[("facts", "text", "4471")],
        notes="Forget is delete-class; declined, so the fact must still be in memory.db.",
    ),
    S(
        "G05_web_fetch_delete_declined",
        "web_fetch",
        "Use web_fetch with method DELETE on https://example.com/arelis-matrix-probe.",
        [],
        gate=("web_fetch",),
        decline=("web_fetch",),
        no_tools_ok=True,
        notes="DELETE is destructive, so it pauses even when asked; decline means no request leaves.",
    ),
]


# ----------------------------------------------------------------------------
# SMS / email test plan items. NOT part of ITEMS: send_sms and send_email stay
# BANNED in the main matrix and the default runner never sees these. They are
# for a separate, opt-in comms mode (not implemented in the runner yet) that
#   * runs in its own data dir holding ONLY the two contact aliases below and
#     the mail/SMS credentials, never the owner's full book;
#   * auto-answers every confirm card itself: allow only when the resolved
#     recipient is in item.recipients AND the body starts with the test tag,
#     otherwise skip;
#   * uses recording stub providers for every item with live_sends == 0, so a
#     gate bug cannot reach a radio;
#   * never retries (no --retry-failed for these ids) and writes one line per
#     real send (item id, tool, provider message id) to a comms ledger with no
#     numbers or addresses.
# Total real sends per run: sum(live_sends) == 3 (2 SMS, 1 email).
# {run} is replaced with a per-run id so the tag is unique and greppable.
# ----------------------------------------------------------------------------
COMMS_TAG = "[Arelis TEST {run}]"
# The test mailbox is supplied by whoever opts in; no address lives in the repo.
COMMS_EMAIL = os.environ.get("ARELIS_MATRIX_TEST_EMAIL", "test-recipient@example.invalid")

COMMS_ITEMS = [
    S(
        "M01_sms_me_live",
        "send_sms",
        "Text myself: " + COMMS_TAG + " automated matrix check, please ignore.",
        ["send_sms"],
        gate=("send_sms",),
        live_sends=1,
        recipients=("me", "myself"),
        timeout=300,
        notes="One real SMS to the user. Pass needs the provider message id; queued is not delivered.",
    ),
    S(
        "M02_sms_wife_live",
        "send_sms",
        "Text my wife: " + COMMS_TAG + " automated matrix check, please ignore.",
        ["send_sms"],
        gate=("send_sms",),
        live_sends=1,
        recipients=("wife",),
        timeout=300,
        notes="One real SMS to the user's wife. Same evidence rule as M01.",
    ),
    S(
        "M03_email_live",
        "send_email",
        "Email "
        + COMMS_EMAIL
        + " with subject '"
        + COMMS_TAG
        + " matrix email check' and body 'Automated Arelis test, please ignore.'",
        ["send_email"],
        gate=("send_email",),
        live_sends=1,
        recipients=(COMMS_EMAIL,),
        timeout=300,
        notes="One real email. Pass needs SMTP acceptance (Message-ID) from the Mailer.",
    ),
    S(
        "M04_sms_declined_stub",
        "send_sms",
        "Text myself: " + COMMS_TAG + " this one must not go out.",
        [],
        gate=("send_sms",),
        decline=("send_sms",),
        all=["did not send"],
        no_tools_ok=True,
        notes="Stub provider. Card fires, runner skips, provider call count must be 0.",
    ),
    S(
        "M05_email_declined_stub",
        "send_email",
        "Email "
        + COMMS_EMAIL
        + " with subject '"
        + COMMS_TAG
        + " must not go out' and body 'declined test'.",
        [],
        gate=("send_email",),
        decline=("send_email",),
        all=["did not send"],
        no_tools_ok=True,
        notes="Stub mailer. Card fires, runner skips, mailer call count must be 0.",
    ),
    S(
        "M06_sms_not_offered_stub",
        "send_sms",
        "How are you today?",
        [],
        no_tools_ok=True,
        notes="Authorization: with no send intent the send tools are hidden. Stub call count 0, no card.",
    ),
]
